services:
  - type: web
    name: sla-fusion-backend
    env: python
    runtime: python3.10
    root: sla_fusion_backend
    plan: free
    autodeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: "8000"

  - type: web
    name: sla-fusion-frontend
    env: node
    runtime: 18
    root: .
    plan: free
    autodeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: "3000"
